### PR TITLE
composer.json: Allow PHP 8

### PR DESCRIPTION
**Pull request by Ayesh**

### CODE REVIEW

**Comment by Ayesh** [comment]
Related: sebastianbergmann/phpunit#4325

**Comment by TomasVotruba** [comment]
This is one of my blockers to try PHP 8.0 in @symplify, @migrify and @rectorphp

Could you release new version so we can try it?

**Comment by sebastianbergmann** [comment]
But 62694a70d608b5c0ba3d9d9c91013b3ebe7a5b01 is released as of version 3.0.2 (tagged June 27, 2020).

**Comment by theseer** [comment]
Maybe something gets confused if this is not explicitly a "release" but merely a tag? I just created a `3.0.2` release from the tag, maybe that helps..

**Comment by TomasVotruba** [comment]
I only reacted to my composer, maybe it was another hidden blocker miss-reporeted by composer.
I'll investigate

Thank you :+1:

**Comment by TomasVotruba** [comment]
It seems it's only tagged since 3.0.2

image

Otherwise there would be more tags mentioned:

image

**Comment by theseer** [comment]
I'm not sure what you are trying to tell me here?

**Comment by TomasVotruba** [comment]
I guess it's not relevant now. I'll be back if the problem still persists.

Thanks

**Comment by TomasVotruba** [comment]
Ah, there is version 3 now. I was using version 2.
My appologies for the confusion.

<br>

I have checked [`CHANGELOG`](https://github.com/phar-io/version/blob/master/CHANGELOG.md), but don't see any BC breaks mentioned. What changed? So I know how to upgrade my code

**Comment by theseer** [comment]
Well, all what is written in the [CANGELOG for 3.0.0](https://github.com/phar-io/version/blob/master/CHANGELOG.md#300---05052020): Strict-Mode, scalar types and PHP 7.2+.

As this is a technical major change, a new major version is required. If your code was compliant already, then of course nothing changed for you.

**Comment by TomasVotruba** [comment]
Ah, I see, that does not change for me. Thanks

**Pull request merged**
